# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sorte"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan Gorman"]
  s.date = "2012-03-31"
  s.description = "Sort your mp3s into folders"
  s.email = "gorman.jan@gmail.com"
  s.executables = ["sorte"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/sorte",
    "lib/sorte.rb",
    "pkg/sorte-0.1.0.gem",
    "sorte.gemspec"
  ]
  s.homepage = "http://github.com/JanGorman/Sorte"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.21"
  s.summary = "Sort a directory of mp3s into folders base on their tags"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_development_dependency(%q<jeweler>, "~> 2.3.9")
      s.add_development_dependency(%q<trollop>, ["~> 1.16.2"])
      s.add_development_dependency(%q<ruby-mp3info>, ["~> 0.7"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.1.3"])
      s.add_dependency(%q<jeweler>, "~> 2.3.9")
      s.add_dependency(%q<trollop>, ["~> 1.16.2"])
      s.add_dependency(%q<ruby-mp3info>, ["~> 0.7"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.1.3"])
    s.add_dependency(%q<jeweler>, "~> 2.3.9")
    s.add_dependency(%q<trollop>, ["~> 1.16.2"])
    s.add_dependency(%q<ruby-mp3info>, ["~> 0.7"])
  end
end

